name: styleme
description: StyleMe - Recomendación inteligente de outfits con Machine Learning
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.1.2

  # HTTP client
  dio: ^5.4.3+1

  # Imagen y cámara
  image_picker: ^1.1.2

  # Corrección de orientación EXIF
  image: ^4.8.0

  # Almacenamiento local
  shared_preferences: ^2.2.3

  # Imágenes en red con caché
  cached_network_image: ^3.3.1

  # Fuente Poppins
  google_fonts: ^6.2.1

  # Utilidades
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
